/* The property's headline number must be the same number everywhere.

   On 2026-09-09 it was not. /organism/ published "59 kept, 106 refused, 64% of
   commits declined" because it counted from timeline.yml, which holds the most
   recent 200 rows. The front door and the public record published 61 and 186
   from the full ledgers. A visitor walking from one to the other got two
   different answers to the question the whole property is built on, and both
   pages looked equally confident.

   Nothing here reads a rendered page: it reads the files the pages are built
   from, so a disagreement fails before anything ships. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const countRows = (file) => readFileSync(file, 'utf8').split('\n').filter((l) => /^- /.test(l)).length;
const scalar = (file, key) => {
  const m = new RegExp(`^\\s*${key}:\\s*(\\d+)\\s*$`, 'm').exec(readFileSync(file, 'utf8'));
  return m ? Number(m[1]) : null;
};

const KEPT = countRows('_data/agent_receipts.yml');
const REFUSED = countRows('_data/agent_receipt_rejections.yml');
const corpus = JSON.parse(readFileSync('workspace/corpus.json', 'utf8'));

test('the ledgers are not empty', () => {
  assert.ok(KEPT > 0 && REFUSED > 0, `kept ${KEPT}, refused ${REFUSED}`);
});

test('the corpus counts match the ledgers it was built from', () => {
  assert.equal(corpus.counts.kept, KEPT, 'corpus.counts.kept');
  assert.equal(corpus.counts.refused, REFUSED, 'corpus.counts.refused');
  assert.equal(corpus.kept.length, KEPT);
  assert.equal(corpus.refused.length, REFUSED);
});

test('the vitals console counts the same ledgers, not a recent window', () => {
  assert.equal(scalar('_data/organism.yml', 'kept'), KEPT,
    'organism.receipts.kept disagrees with agent_receipts.yml');
  assert.equal(scalar('_data/organism.yml', 'declined'), REFUSED,
    'organism.receipts.declined disagrees with agent_receipt_rejections.yml');
  const claims = scalar('_data/organism.yml', 'claims');
  assert.equal(claims, KEPT + REFUSED, 'claims is not kept + declined');
  assert.equal(scalar('_data/organism.yml', 'decline_pct'), Math.round(REFUSED / claims * 100));
});

test('the /inside/ ticket quotes the ledger it was built from', () => {
  /* This one lags by design: experience.yml is regenerated by the nightly
     run, so it can be one refusal behind for a day. The lag is allowed; a
     drift of more than one is a build that did not run. */
  const line = /(\d+) receipts kept · (\d+) claims declined/.exec(readFileSync('_data/experience.yml', 'utf8'));
  assert.ok(line, 'the service ticket no longer prints the counts');
  assert.equal(Number(line[1]), KEPT, 'ticket kept count');
  assert.ok(Math.abs(Number(line[2]) - REFUSED) <= 1,
    `ticket says ${line[2]} declined, the ledger has ${REFUSED}`);
});

test('no page quotes timeline.yml as if it were a total', async () => {
  /* timeline.yml is capped at the most recent 200 rows. /organism/ published
     "106 refused" from it while the ledgers said 186, and the fix was an hour
     old when /about/ printed "200 braided records" from the same file. A
     windowed number presented as a count is the same defect twice. */
  const { readdirSync } = await import('node:fs');
  const pages = readdirSync('.').filter((f) => /\.(md|html)$/.test(f));
  const bad = [];
  for (const f of pages) {
    const src = readFileSync(f, 'utf8');
    if (/site\.data\.timeline\s*\|\s*size/.test(src)) bad.push(f);
  }
  assert.deepEqual(bad, [], `these quote the timeline window as a count: ${bad.join(', ')}`);
});

test('the streak on /about/ is the real one, not the 30 day window', () => {
  /* streak_days and active_days_30d are both computed inside a 30 day window,
     so both cap at 30 and read as facts. /about/ printed "30 consecutive days"
     when the true figure was 44. Same defect as the timeline window, in the
     other direction: understated rather than overstated, still a window
     wearing a count's clothes. */
  const about = readFileSync('about.md', 'utf8');
  assert.ok(!/activity\.streak_days\s*}}/.test(about),
    '/about/ is quoting the 30 day streak; use streak_days_all');
  assert.ok(!/activity\.active_days_30d\s*}}/.test(about),
    '/about/ is quoting active_days_30d; use active_days_all');
  const org = readFileSync('_data/organism.yml', 'utf8');
  const all = Number(/streak_days_all:\s*(\d+)/.exec(org)?.[1]);
  const win = Number(/streak_days:\s*(\d+)/.exec(org)?.[1]);
  assert.ok(Number.isFinite(all), 'streak_days_all is not exported');
  assert.ok(all >= win, `the unbounded streak (${all}) is below the windowed one (${win})`);
});
