/* The property's headline number must be the same number everywhere.

   On 2026-09-09 it was not. /organism/ published "59 kept, 106 refused, 64% of
   commits declined" because it counted from timeline.yml, which holds the most
   recent 200 rows. The front door and the public record published 61 and 186
   from the full ledgers. A visitor walking from one to the other got two
   different answers to the question the whole property is built on, and both
   pages looked equally confident.

   Nothing here reads a rendered page: it reads the files the pages are built
   from, so a disagreement fails before anything ships. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const countRows = (file) => readFileSync(file, 'utf8').split('\n').filter((l) => /^- /.test(l)).length;
const scalar = (file, key) => {
  const m = new RegExp(`^\\s*${key}:\\s*(\\d+)\\s*$`, 'm').exec(readFileSync(file, 'utf8'));
  return m ? Number(m[1]) : null;
};

const KEPT = countRows('_data/agent_receipts.yml');
const REFUSED = countRows('_data/agent_receipt_rejections.yml');
const corpus = JSON.parse(readFileSync('workspace/corpus.json', 'utf8'));

test('the ledgers are not empty', () => {
  assert.ok(KEPT > 0 && REFUSED > 0, `kept ${KEPT}, refused ${REFUSED}`);
});

test('the corpus counts match the ledgers it was built from', () => {
  assert.equal(corpus.counts.kept, KEPT, 'corpus.counts.kept');
  assert.equal(corpus.counts.refused, REFUSED, 'corpus.counts.refused');
  assert.equal(corpus.kept.length, KEPT);
  assert.equal(corpus.refused.length, REFUSED);
});

test('the vitals console counts the same ledgers, not a recent window', () => {
  assert.equal(scalar('_data/organism.yml', 'kept'), KEPT,
    'organism.receipts.kept disagrees with agent_receipts.yml');
  assert.equal(scalar('_data/organism.yml', 'declined'), REFUSED,
    'organism.receipts.declined disagrees with agent_receipt_rejections.yml');
  const claims = scalar('_data/organism.yml', 'claims');
  assert.equal(claims, KEPT + REFUSED, 'claims is not kept + declined');
  assert.equal(scalar('_data/organism.yml', 'decline_pct'), Math.round(REFUSED / claims * 100));
});

test('the /inside/ ticket quotes the ledger it was built from', () => {
  /* This one lags by design: experience.yml is regenerated by the nightly
     run, so it can be one refusal behind for a day. The lag is allowed; a
     drift of more than one is a build that did not run. */
  const line = /(\d+) receipts kept · (\d+) claims declined/.exec(readFileSync('_data/experience.yml', 'utf8'));
  assert.ok(line, 'the service ticket no longer prints the counts');
  assert.equal(Number(line[1]), KEPT, 'ticket kept count');
  assert.ok(Math.abs(Number(line[2]) - REFUSED) <= 1,
    `ticket says ${line[2]} declined, the ledger has ${REFUSED}`);
});
