/* Every page the browser's bookmarks list offers must be a page this site
   actually publishes, and every page it publishes must be offered.

   The launch orphaned sixteen surfaces in one commit and no test noticed,
   because every one of them still answered 200 at its own URL. Reachability
   is not something a status code can tell you. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, statSync } from 'node:fs';

const mac = readFileSync('workspace/mac.js', 'utf8');

const listed = (() => {
  const start = mac.indexOf('const SITE_PAGES = [');
  assert.ok(start > 0, 'SITE_PAGES is gone: the browser has no bookmarks');
  const block = mac.slice(start, mac.indexOf('\n  ];', start));
  /* Titles containing an apostrophe are written in double quotes, so a
     single-quote-only pattern silently dropped them and the test then
     reported a page as unreachable that was listed all along. */
  return [...block.matchAll(/\['(\/[^']*)',\s*(?:'([^']*)'|"([^"]*)")/g)]
    .map((m) => ({ href: m[1], title: m[2] ?? m[3] }));
})();

const excluded = (() => {
  const out = new Set();
  let inside = false;
  for (const line of readFileSync('_config.yml', 'utf8').split('\n')) {
    if (/^exclude:\s*$/.test(line)) { inside = true; continue; }
    if (!inside) continue;
    if (/^\S/.test(line)) break;
    const m = /^\s*-\s*(\S+)/.exec(line);
    if (m) out.add(m[1]);
  }
  return out;
})();

const published = (() => {
  const out = new Map();
  for (const name of readdirSync('.')) {
    if (!/\.(md|markdown)$/.test(name) || excluded.has(name)) continue;
    if (!statSync(name).isFile()) continue;
    const perm = /^permalink:\s*(\S+)/m.exec(readFileSync(name, 'utf8').slice(0, 900));
    if (perm) out.set(perm[1].replace(/^["']|["']$/g, ''), name);
  }
  return out;
})();

test('the browser lists something', () => {
  assert.ok(listed.length >= 10, `only ${listed.length} bookmarks`);
});

test('every bookmark points at a page this site publishes', () => {
  for (const { href, title } of listed) {
    /* /journal/book/ is generated by journal-book.md under a nested permalink */
    if (published.has(href)) continue;
    const nested = [...published.keys()].some((p) => href.startsWith(p));
    assert.ok(nested, `"${title}" points at ${href}, which nothing publishes`);
  }
});

test('every published page is offered somewhere a visitor can reach', () => {
  const offered = new Set(listed.map((l) => l.href));
  const missing = [];
  for (const [href, file] of published) {
    if (offered.has(href)) continue;
    /* the front door and the workspace are reached without a bookmark */
    if (href === '/' || href.startsWith('/workspace')) continue;
    missing.push(`${href} (${file})`);
  }
  assert.deepEqual(missing, [], `published but unreachable: ${missing.join(', ')}`);
});
