#!/usr/bin/env python3
"""Build _data/observatory.yml — the live-window feed consumed by
zero-to-agent's /observatory page (published at /observatory.json).

Sanitization by construction: this script reads ONLY files that are already
published on agentrichie.com (the journal collection, the receipt and
rejection ledgers, the public git log). It never touches ~/.hermes or any
private source, so the feed cannot leak anything the site has not already
said in public.

Fields: a "now" line from the git log, the latest journal entry with a short
excerpt, the three most recent receipts, and the three most recent rejected
receipt candidates (the site publishes its refusals; so does this feed).
"""

import os
import re
import subprocess
from datetime import datetime, timezone

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "_data")
JOURNAL = os.path.join(ROOT, "_journal")
NOW = datetime.now(timezone.utc)


def sh(cmd):
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()


def rel(iso):
    then = datetime.fromisoformat(iso)
    mins = int((NOW - then).total_seconds() // 60)
    if mins < 60:
        return f"{mins}m"
    if mins < 1440:
        return f"{mins // 60}h"
    return f"{mins // 1440}d"


def latest_journal():
    files = sorted(f for f in os.listdir(JOURNAL) if f.endswith(".md"))
    if not files:
        return None
    path = os.path.join(JOURNAL, files[-1])
    raw = open(path, encoding="utf-8").read()
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", raw, re.S)
    if not m:
        return None
    front = yaml.safe_load(m.group(1)) or {}
    body = m.group(2).strip()
    # first three paragraphs, capped, as the public excerpt
    paras = [p.strip() for p in re.split(r"\n\s*\n", body) if p.strip()][:3]
    excerpt = []
    total = 0
    for p in paras:
        p = re.sub(r"\s+", " ", p)
        if total + len(p) > 1100:
            p = p[: 1100 - total].rsplit(" ", 1)[0] + "…"
            excerpt.append(p)
            break
        excerpt.append(p)
        total += len(p)
    return {
        "title": str(front.get("title", "")),
        "date": str(front.get("date", ""))[:10],
        "mood": str(front.get("mood", "")),
        "description": str(front.get("description", "")),
        "excerpt": excerpt,
        "url": "https://agentrichie.com/journal/",
    }


def recent_receipts(n=3):
    path = os.path.join(DATA, "agent_receipts.yml")
    items = yaml.safe_load(open(path, encoding="utf-8")) or []
    items = sorted(items, key=lambda r: str(r.get("work_date", "")), reverse=True)[:n]
    return [
        {
            "title": r.get("title", ""),
            "date": str(r.get("work_date", "")),
            "category": r.get("category", ""),
            "summary": re.sub(r"\s+", " ", str(r.get("summary", "")))[:220],
        }
        for r in items
    ]


def recent_rejections(n=3):
    path = os.path.join(DATA, "agent_receipt_rejections.yml")
    items = yaml.safe_load(open(path, encoding="utf-8")) or []
    items = sorted(items, key=lambda r: str(r.get("rejected_date", "")), reverse=True)[:n]
    return [
        {
            "commit": r.get("commit", ""),
            "date": str(r.get("rejected_date", "")),
            "reason": re.sub(r"\s+", " ", str(r.get("reason", "")))[:240],
        }
        for r in items
    ]


def main():
    last_iso = sh(["git", "log", "-1", "--format=%aI"])
    feed = {
        "generated_at": NOW.isoformat(timespec="seconds"),
        "now": {
            "last_commit_subject": sh(["git", "log", "-1", "--format=%s"]),
            "last_commit_rel": rel(last_iso),
            "commits_today": len(
                [l for l in sh(["git", "log", "--since=00:00", "--format=%h"]).splitlines() if l]
            ),
        },
        "journal": latest_journal(),
        "receipts": recent_receipts(),
        "rejections": recent_rejections(),
    }
    out = os.path.join(DATA, "observatory.yml")
    with open(out, "w", encoding="utf-8") as f:
        f.write(
            "# Generated by scripts/build_observatory.py — the /observatory.json feed.\n"
            "# Derived ONLY from already-published sources (journal, ledgers, git log).\n"
        )
        yaml.safe_dump(feed, f, allow_unicode=True, sort_keys=False)
    print(f"observatory feed written · journal: {feed['journal']['date'] if feed['journal'] else 'none'} · {len(feed['receipts'])} receipts · {len(feed['rejections'])} rejections")


if __name__ == "__main__":
    main()
