#!/usr/bin/env python3
"""Emit _data/provenance.yml: this homepage's birth certificate.

Reads git log for the overnight front-door files and cross-references
agent_receipts.yml evidence commits. Consumed by the M6 provenance card
on the homepage. A missing file (first run, before those paths exist) is
an honest gap, not a reason to invent rows.

    /usr/bin/python3 scripts/build_provenance.py
"""
from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
RECEIPTS = ROOT / "_data" / "agent_receipts.yml"
OUT = ROOT / "_data" / "provenance.yml"

# The front door. Git history of these paths is the page's own record.
TRACKED = (
    "index.md",
    "assets/js/overnight.js",
    "assets/lib/journey.mjs",
    "assets/css/overnight.css",
)


def sh(args: list[str]) -> str:
    return subprocess.run(
        args, cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def load_yaml(path: Path):
    if not path.exists():
        return []
    return yaml.safe_load(path.read_text()) or []


def git_sha() -> str:
    return sh(["git", "rev-parse", "--short", "HEAD"])


def git_commits() -> list[dict]:
    """Newest-first commits that actually touched a front-door file."""
    existing = [p for p in TRACKED if (ROOT / p).exists()]
    if not existing:
        return []
    fmt = "%h\x1f%cs\x1f%s"
    out = subprocess.run(
        ["git", "log", "-40", f"--pretty=format:{fmt}", "--"] + existing,
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    rows = []
    seen = set()
    for line in out.splitlines():
        if not line.strip():
            continue
        sha, date, subject = line.split("\x1f", 2)
        if sha in seen:
            continue
        seen.add(sha)
        rows.append({"sha": sha, "date": date, "subject": subject})
    return rows


def receipt_ids_for(commits: list[dict]) -> list[str]:
    """Receipts whose evidence cites a commit that touched the front door."""
    shas = {c["sha"] for c in commits}
    found = []
    for rec in load_yaml(RECEIPTS):
        rid = rec.get("id")
        if not rid:
            continue
        hits = False
        for ev in rec.get("evidence") or []:
            commit = str(ev.get("commit") or "")
            if commit and commit in shas:
                hits = True
                break
        if hits:
            found.append(rid)
    return found


def main() -> None:
    now = datetime.now(timezone.utc)
    sha = git_sha()
    commits = git_commits()
    receipts = receipt_ids_for(commits)
    doc = {
        "built_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "built_at_iso": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "sha": sha,
        "homepage_commits": commits,
        "receipt_ids": receipts,
        "tracked": list(TRACKED),
    }
    header = (
        "# AUTO-GENERATED by scripts/build_provenance.py. The homepage's birth\n"
        "# certificate: the build that produced it, the commits that touched the\n"
        "# front door, and any receipts whose evidence cites those commits.\n"
        "# Single writer. Do not hand-edit.\n"
    )
    OUT.write_text(header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True))
    print(
        f"provenance: sha {sha} · {len(commits)} front-door commits · "
        f"{len(receipts)} receipt(s)"
    )


if __name__ == "__main__":
    main()
