#!/usr/bin/env python3
"""Fold a recorded pipeline run (.tape-run.json, written by tape_lib.sh)
into the published Service Tape: _data/tape/YYYY-MM-DD.yml plus the
_data/tape_index.yml episode list.

A tape is one night of real service, enriched from the same already-public
sources the rest of the site renders from:
  - the run's step labels, real timings, and exit statuses (tape_lib.sh)
  - that date's commits and their receipt/declined adjudications (timeline.yml)
  - that date's journal entry, if the night left one (_journal/)
  - the health verdict the vitals pass computed during the run (organism.yml)

Honesty rules: nothing here is invented or estimated. If a source is missing
the field is omitted, never faked. One tape per date — a later run the same
night overwrites (the last full service is the night's tape). Keeps 90 nights.
"""

import json
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUN_FILE = os.path.join(ROOT, ".tape-run.json")
TAPE_DIR = os.path.join(ROOT, "_data", "tape")
INDEX_FILE = os.path.join(ROOT, "_data", "tape_index.yml")
KEEP_NIGHTS = 90


def load_yaml(rel):
    path = os.path.join(ROOT, "_data", rel)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return yaml.safe_load(f)


def journal_for(date):
    jdir = os.path.join(ROOT, "_journal")
    if not os.path.isdir(jdir):
        return None
    for name in sorted(os.listdir(jdir)):
        if not name.startswith(date):
            continue
        fm = {}
        with open(os.path.join(jdir, name)) as f:
            text = f.read()
        m = re.match(r"---\n(.*?)\n---", text, re.S)
        if m:
            try:
                fm = yaml.safe_load(m.group(1)) or {}
            except yaml.YAMLError:
                fm = {}
        return {
            "title": fm.get("title"),
            "mood": fm.get("mood"),
            "url": "/journal/" + name.replace(".md", "") + "/",
        }
    return None


def main():
    if not os.path.exists(RUN_FILE):
        print("tape: no run record — nothing to publish")
        return 0
    with open(RUN_FILE) as f:
        run = json.load(f)

    date = run.get("date")
    if not date:
        print("tape: run record has no date — skipping", file=sys.stderr)
        return 1

    timeline = load_yaml("timeline.yml") or []
    day = [t for t in timeline if t.get("date") == date and t.get("type") == "commit"]
    commits = [
        {
            "sha": c.get("sha"),
            "subject": c.get("subject"),
            "status": c.get("status") or "log",
            "receipt_id": c.get("receipt_id"),
            "rejection_reason": c.get("rejection_reason"),
        }
        for c in day
    ]

    org = load_yaml("organism.yml") or {}
    health = (org.get("health") or {}).get("verdict")

    steps = run.get("steps", [])
    tape = {
        "date": date,
        "started": run.get("started"),
        "ended": run.get("ended"),
        "trigger": run.get("trigger", "manual"),
        "steps": steps,
        "steps_ok": sum(1 for s in steps if s.get("status") == "ok"),
        "steps_total": len(steps),
        "commits": commits,
        "receipts_kept": sum(1 for c in commits if c["status"] == "receipt"),
        "claims_declined": sum(1 for c in commits if c["status"] == "declined"),
    }
    if health:
        tape["health_verdict"] = health
    j = journal_for(date)
    if j and j.get("title"):
        tape["journal"] = j

    os.makedirs(TAPE_DIR, exist_ok=True)
    out = os.path.join(TAPE_DIR, f"{date}.yml")
    header = (
        "# AUTO-GENERATED by scripts/build_tape.py from a real pipeline run.\n"
        "# One night of the Service Tape, replayed at /tonight/. Do not hand-edit:\n"
        "# every timestamp and status here was recorded, not written.\n"
    )
    with open(out, "w") as f:
        f.write(header)
        yaml.safe_dump(tape, f, sort_keys=False, allow_unicode=True)

    # Re-enrich recent tapes: a night's own stewardship commit lands in git
    # *after* its run recorded, so each run refreshes the last few tapes'
    # commit lists and journal pointers from the current timeline. Tapes
    # converge to the truth; timings are never touched.
    def enrich(path, tdate):
        with open(path) as f:
            t = yaml.safe_load(f) or {}
        tday = [
            c for c in timeline if c.get("date") == tdate and c.get("type") == "commit"
        ]
        if tday:
            t["commits"] = [
                {
                    "sha": c.get("sha"),
                    "subject": c.get("subject"),
                    "status": c.get("status") or "log",
                    "receipt_id": c.get("receipt_id"),
                    "rejection_reason": c.get("rejection_reason"),
                }
                for c in tday
            ]
            t["receipts_kept"] = sum(1 for c in t["commits"] if c["status"] == "receipt")
            t["claims_declined"] = sum(1 for c in t["commits"] if c["status"] == "declined")
        tj = journal_for(tdate)
        if tj and tj.get("title"):
            t["journal"] = tj
        with open(path, "w") as f:
            f.write(header)
            yaml.safe_dump(t, f, sort_keys=False, allow_unicode=True)

    prior = sorted(
        (n[:-4] for n in os.listdir(TAPE_DIR) if n.endswith(".yml")), reverse=True
    )
    for tdate in prior[:4]:
        if tdate != date:
            enrich(os.path.join(TAPE_DIR, tdate + ".yml"), tdate)

    # prune + index
    nights = sorted(
        (n[:-4] for n in os.listdir(TAPE_DIR) if n.endswith(".yml")), reverse=True
    )
    for old in nights[KEEP_NIGHTS:]:
        os.remove(os.path.join(TAPE_DIR, old + ".yml"))
    nights = nights[:KEEP_NIGHTS]

    index = []
    for n in nights:
        with open(os.path.join(TAPE_DIR, n + ".yml")) as f:
            t = yaml.safe_load(f) or {}
        index.append(
            {
                "date": n,
                "trigger": t.get("trigger"),
                "steps_ok": t.get("steps_ok"),
                "steps_total": t.get("steps_total"),
                "receipts_kept": t.get("receipts_kept", 0),
                "claims_declined": t.get("claims_declined", 0),
                "journal_title": (t.get("journal") or {}).get("title"),
                "health_verdict": t.get("health_verdict"),
            }
        )
    with open(INDEX_FILE, "w") as f:
        f.write(
            "# AUTO-GENERATED by scripts/build_tape.py — the Service Tape episode\n"
            "# list, newest first. Rendered by /tape/.\n"
        )
        yaml.safe_dump(index, f, sort_keys=False, allow_unicode=True)

    os.remove(RUN_FILE)
    print(f"tape: published {date} ({len(steps)} steps, {len(commits)} commits)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
