#!/usr/bin/env python3
"""Build a unified timeline data file for the self-documenting /changelog.

Braids four public sources into one date-sorted ledger:
  - git commits        (what physically changed)
  - agent receipts     (commits that earned public proof)
  - declined receipts  (commits deliberately NOT claimed)
  - journal entries    (the narrative for the day)

Output: _data/timeline.yml  (consumed by changelog.md at build time)

This is intentionally re-runnable. Richie's nightly cron can call it so the
changelog stays current without hand-editing:
    python3 scripts/build_timeline.py
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
RECEIPTS = ROOT / "_data" / "agent_receipts.yml"
REJECTIONS = ROOT / "_data" / "agent_receipt_rejections.yml"
JOURNAL_DIR = ROOT / "_journal"
OUT = ROOT / "_data" / "timeline.yml"
REPO = "https://github.com/AriNova1/richie-jerimovich"

# Pure generated-artifact refresh commits keep /changelog current, but listing
# those commits inside the generated changelog creates an impossible self-hash
# loop: committing the changelog changes the commit hash the changelog would
# need to contain. Keep the public timeline focused on substantive site work.
MAINTENANCE_SUBJECT_PREFIXES = (
    "chore: refresh changelog",
    "chore: nightly refresh",
    "Refresh changelog",
)


def load_yaml(path: Path):
    if not path.exists():
        return []
    return yaml.safe_load(path.read_text()) or []


def git_commits(limit: int = 200):
    """Return [{sha, date, subject}] newest-first."""
    fmt = "%h\x1f%cs\x1f%s"  # short-sha, committer-date (YYYY-MM-DD), subject
    out = subprocess.run(
        ["git", "log", f"-{limit}", f"--pretty=format:{fmt}"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    rows = []
    for line in out.splitlines():
        if not line.strip():
            continue
        sha, date, subject = line.split("\x1f", 2)
        rows.append({"sha": sha, "date": date, "subject": subject})
    return rows


def main() -> int:
    receipts = load_yaml(RECEIPTS)
    rejections = load_yaml(REJECTIONS)

    # Map every commit SHA that earned a receipt -> receipt summary.
    receipt_by_sha = {}
    for r in receipts:
        for ev in r.get("evidence", []) or []:
            sha = (ev.get("commit") or "").strip()
            if sha:
                receipt_by_sha[sha[:7]] = {"id": r.get("id"), "title": r.get("title")}

    reject_by_sha = {
        (r.get("commit") or "").strip()[:7]: r.get("reason")
        for r in rejections if r.get("commit")
    }

    events = []

    # Commits, enriched with whether they became a receipt or were declined.
    for c in git_commits():
        if any(c["subject"].startswith(prefix) for prefix in MAINTENANCE_SUBJECT_PREFIXES):
            continue
        sha7 = c["sha"][:7]
        status, receipt, reason = "plain", None, None
        if sha7 in receipt_by_sha:
            status, receipt = "receipt", receipt_by_sha[sha7]
        elif sha7 in reject_by_sha:
            status, reason = "declined", reject_by_sha[sha7]
        events.append({
            "type": "commit",
            "date": c["date"],
            "sha": c["sha"],
            "subject": c["subject"],
            "status": status,
            "receipt_id": (receipt or {}).get("id"),
            "receipt_title": (receipt or {}).get("title"),
            "rejection_reason": reason,
            "url": f"{REPO}/commit/{c['sha']}",
        })

    timeline = sorted(events, key=lambda e: (e["date"], e["sha"]), reverse=True)

    header = (
        "# AUTO-GENERATED by scripts/build_timeline.py — do not hand-edit.\n"
        "# Unified commit/receipt/declined ledger for /changelog.\n"
    )
    OUT.write_text(header + yaml.safe_dump(timeline, sort_keys=False, allow_unicode=True))

    n_receipt = sum(1 for e in timeline if e["status"] == "receipt")
    n_declined = sum(1 for e in timeline if e["status"] == "declined")
    print(f"wrote {len(timeline)} commits -> {OUT.relative_to(ROOT)} "
          f"({n_receipt} with receipts, {n_declined} declined)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
